osx_image: xcode8

podfile: data-structures/Podfile
language: objective-c
xcode_workspace: data-structures.xcworkspace # path to your xcodeproj folder

env:
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='10.1' ios_device='iPhone SE'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='9.3'  ios_device='iPhone 6'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='8.1'  ios_device='iPhone 4s'

before_install: |
  ios_simulator_udid=$(instruments -s devices | grep "$ios_device ($ios_version)" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')
  echo "Prelaunching iOS simulator with UDID $ios_simulator_udid"
